### ISSUE TITLE
Excel squeezes columns

### ISSUE THREAD

**Issue by bildlich** [Dobiasd/img2xls#3]
Nice little program!
When opening a generated image in Excel (Mac 2011 in my case) the columns are squeezed so much that the image becomes unrecognizable. Is there a way to prevent this from happening?

![screenshot 2015-05-15 18 26 29](https://cloud.githubusercontent.com/assets/501617/7657171/30f27db6-fb30-11e4-9d92-82257202eb3b.png)

**Update** I found the following solution:
1. Select the whole artwork
2. Check what row height Excel has chosen at _Format->Rows->Height…_
3. Go to _Format->Column->Width…_ and enter the same value as the height to achieve square cells.

**Comment by Dobiasd** [comment]
Thanks. :)

You could also try to start the script with

```
python3 img2xls.py mac image.png
```

instead of

```
python3 img2xls.py libre image.png
```

**Comment by bildlich** [comment]
Interesting. Might be a good idea to document these commands?

**Comment by Dobiasd** [comment]
I believe this feature was added shotly after you initially asked here.
Now it also is [documented](https://github.com/Dobiasd/img2xls/commit/c6a445efc8dea4c0daee759b34d1409f71524750). ;)
